"""Horizons on a three-dimensional slice: apparent by flow, event by running time backwards.

Issue #50. Two surfaces that are easy to confuse and are found by opposite
means.

**The apparent horizon** is the outermost marginally outer trapped surface
*on one slice*: the outward null expansion

    Theta = D_i s^i + K_ij s^i s^j - K

vanishes on it, where ``s^i`` is the outward unit normal within the slice.
That is a condition on a single slice, so it is computable during a run, and
it is what a code reports as "the horizon formed at ``t = ...``". It is also
slicing-dependent: a horizon-avoiding slicing has none, which
:mod:`particlesim.analysis.spherical_diagnostics` says at length about
polar-areal coordinates.

**The event horizon** is the boundary of the past of future null infinity --
a statement about the whole spacetime, not one slice, and so only
computable afterwards. It is generated by null geodesics that neither escape
nor fall in.

**Why one is flowed forwards and the other backwards.** The apparent horizon
is found by moving a trial surface in its own normal direction at speed
``-Theta`` until it stops. That flow is parabolic and its fixed point is
attracting, so it converges from a guess that need not be close. The event
horizon is the opposite: outgoing null surfaces near it *diverge* from it
towards the future, exponentially, at the surface gravity -- which is why
it cannot be found by integrating forwards, and why integrating the same
surfaces *backwards* converges onto it from either side. Measured below at a
rate that matches ``e^(-kappa t)`` with ``kappa = 1/(4M)``.

**Both surfaces are stored as a radius per direction, not as a level-set
field.** ``Theta`` and the null condition are both computed from a field
``F`` whose zero set is the surface, because the geometry they need is
differenced on the grid -- but ``F`` is *rebuilt* from ``h(theta, phi)``
every iteration rather than evolved, so it accumulates nothing.

That is not the obvious design and it is not a stylistic preference. Both
flows were first written as evolutions of ``F`` on the grid and both failed,
in different ways: the apparent-horizon flow because a varying step puts
structure into ``grad grad F``, which is exactly what the divergence term of
``Theta`` differentiates, and the backward null flow because
``d_t F = beta^i d_i F - alpha |grad F|`` is a Hamilton-Jacobi equation and
steepening is what those do -- it overflowed to ``inf`` and then ``NaN``.
The failures and their measurements are recorded on
:func:`find_apparent_horizon` and :func:`event_horizon_flow`, because the
symptoms both look like something else: a bad initial guess in the first
case, and an unstable spacetime in the second.

Rebuilding is stronger than the reinitialisation a level-set method would
normally use. It is worth being clear about what it does *not* buy, though:
``Theta`` depends on ``F`` only through the direction of its gradient, so it
is invariant under ``F -> G(F)`` for increasing ``G``, which means gradient
drift was never going to move the fixed point. It was the stability and the
dynamic range that needed fixing, not the answer.

**What is assumed, and where it breaks.** Areas and radii are read off by
casting rays from a centre, so the surface has to be star-shaped about that
centre. One black hole is; the common horizon just after a merger is not,
and neither is the pair-of-pants surface that a binary's event horizon
sweeps out. Finding those needs a representation that is not a radius per
direction, and this module does not have one.

**Measured, against exact Schwarzschild in isotropic coordinates**, where
the horizon is at ``r = M/2`` with area ``16 pi M^2`` and so irreducible
mass exactly ``M``. On a box of extent ``4M``, from a trial radius of
``0.9M``, 400 iterations at ``degree=2``:

    n     spacing   radius/M   area/(16 pi M^2)   M_irr/M    max|Theta| M
    32     0.1250   0.498451       0.960773      0.980190    2.35e-02
    48     0.0833   0.498712       0.995627      0.997811    4.94e-03
    64     0.0625   0.499577       0.999311      0.999656    2.28e-03
    96     0.0417   0.499951       0.999996      0.999998    4.63e-04

No order should be read off that last row: by ``n = 96`` the mass error is
2e-06 and the flow's own convergence is the limit rather than the grid's.
Between 48 and 64 the mass error falls by 6.4 for a spacing ratio of 1.33,
and the honest summary is that the whole thing is resolution-limited by how
many cells lie between the puncture and the horizon -- six at ``n = 32``,
eighteen at ``n = 96``.

**And against a surface that is not a coordinate sphere.** Casting rays from
a centre offset from the puncture leaves the same physical surface with an
angle-dependent radius, and the area has to be unchanged. At ``n = 64`` with
``degree=4``:

    offset/M   (max-min)/mean of h   area/(16 pi M^2)   M_irr/M
      0.00           2.3e-15             0.999455       0.999727
      0.10           4.0e-01             0.999399       0.999700
      0.20           8.3e-01             0.999579       0.999789

A radius varying by 83% across directions, and the area still good to four
digits. That is the test of :func:`surface_area`'s angular derivative terms,
which a coordinate sphere does not exercise at all.

**The event horizon, checked against the surface gravity.** Backward null
surfaces must converge onto the horizon at ``kappa``, and for Schwarzschild
``d/dr(alpha/psi^2)`` at ``r = M/2`` is exactly ``1/(4M)``. Integrating back
to ``t = -20M`` at ``n = 64``:

    start/M    r(-20M)/M    measured rate    rate/kappa
      0.60      0.500618       0.2531          1.013
      0.70      0.501157       0.2558          1.023
      1.00      0.502544       0.2619          1.048
      0.42      0.499409       0.2468          0.987
      0.35      0.498773       0.2433          0.973

From either side, at the surface gravity to within 5%. The rate is an
analytic number that nothing else in this module knows about.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from functools import lru_cache
from typing import Any

import numpy as np
from scipy.ndimage import map_coordinates

from particlesim.core.grid import derivative

DIMENSION = 3
INDICES = tuple(range(DIMENSION))


def _pair(i: int, j: int) -> str:
    """The stored name of a symmetric component, which only keeps ``i <= j``."""
    return f"{min(i, j)}{max(i, j)}"


@dataclass(frozen=True, eq=False)
class Slice:
    """``gamma_ij``, ``K_ij``, the lapse and the shift, on a Cartesian grid.

    ``fields`` uses the same names as
    :func:`particlesim.solvers.nr.bssn.physical_slice_arrays` -- ``gamma00``
    through ``gamma22`` and ``K00`` through ``K22``, upper triangle only,
    plus ``alpha`` and ``beta0..2`` -- so the output of a BSSN run is a valid
    argument without translation.

    ``centre`` is the coordinate point rays are cast from, in the same
    coordinates as the grid. It is not the origin of the array: puncture
    data is deliberately staggered half a cell off the box centre, so the
    caller has to say where the hole is.

    ``eq=False`` for the same reason the boundary condition has it: this
    holds arrays, and instances get used as cache keys.
    """

    fields: Mapping[str, Any]
    spacing: tuple[float, ...]
    centre: tuple[float, ...] = (0.0, 0.0, 0.0)
    order: int = 4

    def __post_init__(self) -> None:
        # The inverse metric, its derivatives and the Christoffels depend on
        # the slice alone, while the flow asks for them once per iteration --
        # hundreds of times over, for twenty-seven Christoffel components
        # each built from three grid derivatives. Cached here so they are
        # built once per slice instead.
        object.__setattr__(self, "_cache", {})
        missing = [
            name
            for name in (
                [f"gamma{_pair(i, j)}" for i in INDICES for j in range(i, DIMENSION)]
                + [f"K{_pair(i, j)}" for i in INDICES for j in range(i, DIMENSION)]
            )
            if name not in self.fields
        ]
        if missing:
            raise ValueError(
                f"the slice is missing {missing}: an expansion needs the full "
                "three-metric and extrinsic curvature, not a BSSN state -- pass "
                "physical_slice_arrays(state) instead"
            )

    @property
    def shape(self) -> tuple[int, ...]:
        return tuple(np.asarray(self.fields["gamma00"]).shape)

    def coordinates(self) -> tuple[np.ndarray, ...]:
        """The grid's coordinates measured from :attr:`centre`."""
        axes = [
            np.arange(count) * self.spacing[axis] - self.centre[axis]
            for axis, count in enumerate(self.shape)
        ]
        return tuple(np.meshgrid(*axes, indexing="ij"))

    def metric(self) -> list[list[np.ndarray]]:
        return [
            [np.asarray(self.fields[f"gamma{_pair(i, j)}"], dtype=float) for j in INDICES]
            for i in INDICES
        ]

    def extrinsic(self) -> list[list[np.ndarray]]:
        return [
            [np.asarray(self.fields[f"K{_pair(i, j)}"], dtype=float) for j in INDICES]
            for i in INDICES
        ]

    def _cached(self, name: str, build):
        cache = self._cache
        if name not in cache:
            cache[name] = build()
        return cache[name]

    def inverse_metric(self) -> list[list[np.ndarray]]:
        """``gamma^ij`` by the adjugate, which for three by three is explicit."""
        return self._cached("inverse", self._build_inverse_metric)

    def _build_inverse_metric(self) -> list[list[np.ndarray]]:
        g = self.metric()
        cofactor = [[None] * DIMENSION for _ in INDICES]
        for i in INDICES:
            for j in INDICES:
                a, b = (i + 1) % 3, (i + 2) % 3
                c, d = (j + 1) % 3, (j + 2) % 3
                cofactor[i][j] = g[a][c] * g[b][d] - g[a][d] * g[b][c]
        determinant = g[0][0] * cofactor[0][0] + g[0][1] * cofactor[0][1] + g[0][2] * cofactor[0][2]
        if np.any(determinant <= 0.0):
            raise ValueError(
                "the three-metric is not positive definite somewhere on the grid "
                f"(smallest determinant {float(np.min(determinant)):.3e}): a "
                "puncture sitting on a grid point does this"
            )
        return [[cofactor[j][i] / determinant for j in INDICES] for i in INDICES]

    def metric_derivative(self) -> list[list[list[np.ndarray]]]:
        """``d_k gamma_ij``, differenced on the grid without wrapping."""
        return self._cached("d_metric", self._build_metric_derivative)

    def _build_metric_derivative(self) -> list[list[list[np.ndarray]]]:
        g = self.metric()
        return [
            [
                [derivative(g[i][j], k, self.spacing[k], order=self.order) for j in INDICES]
                for i in INDICES
            ]
            for k in INDICES
        ]

    def christoffel(self) -> list[list[list[np.ndarray]]]:
        """``Gamma^k_ij`` of the three-metric, as ``[k][i][j]``."""
        return self._cached("christoffel", self._build_christoffel)

    def _build_christoffel(self) -> list[list[list[np.ndarray]]]:
        inverse = self.inverse_metric()
        d = self.metric_derivative()
        return [
            [
                [
                    sum(inverse[k][l] * (d[i][l][j] + d[j][l][i] - d[l][i][j]) / 2 for l in INDICES)
                    for j in INDICES
                ]
                for i in INDICES
            ]
            for k in INDICES
        ]


def expansion(level_set, slice_: Slice) -> np.ndarray:
    """``Theta`` of the level sets of ``level_set``, on the whole grid.

    ``Theta = D_i s^i + K_ij s^i s^j - K`` with
    ``s_i = d_i F / sqrt(gamma^kl d_k F d_l F)``, so ``F`` must increase
    outwards: with the opposite sign the *ingoing* expansion is returned and
    a search converges onto nothing.

    Computed everywhere rather than on a surface because the geometry's
    derivatives are grid derivatives. Interpolating ``gamma`` to a surface
    and differencing there would put the interpolation error inside a
    derivative; this way only the finished ``Theta`` is interpolated.
    """
    field = np.asarray(level_set, dtype=float)
    inverse = slice_.inverse_metric()
    gradient = [derivative(field, i, slice_.spacing[i], order=slice_.order) for i in INDICES]

    norm_squared = sum(inverse[i][j] * gradient[i] * gradient[j] for i in INDICES for j in INDICES)
    if np.any(norm_squared <= 0.0):
        raise ValueError(
            "the level set has a vanishing gradient somewhere, so it has no "
            "normal there: a flow that has folded the surface onto itself does "
            "this, and so does a constant initial field"
        )
    norm = np.sqrt(norm_squared)
    lower = [gradient[i] / norm for i in INDICES]
    upper = [sum(inverse[i][j] * lower[j] for j in INDICES) for i in INDICES]

    d_lower = [
        [derivative(lower[j], i, slice_.spacing[i], order=slice_.order) for j in INDICES]
        for i in INDICES
    ]
    connection = slice_.christoffel()
    divergence = sum(
        inverse[i][j] * (d_lower[i][j] - sum(connection[k][i][j] * lower[k] for k in INDICES))
        for i in INDICES
        for j in INDICES
    )

    curvature = slice_.extrinsic()
    projected = sum(curvature[i][j] * upper[i] * upper[j] for i in INDICES for j in INDICES)
    trace = sum(inverse[i][j] * curvature[i][j] for i in INDICES for j in INDICES)
    return divergence + projected - trace


# --- the surface, as a radius per direction ------------------------------


def angular_grid(theta_count: int = 24, phi_count: int = 48):
    """A Gauss-Legendre grid in ``cos theta`` and a uniform one in ``phi``.

    Gauss-Legendre because the area integral is ``int dcos(theta) dphi``, and
    a uniform grid in ``theta`` puts points where the integrand has a
    ``sin theta`` that a midpoint rule then has to resolve. With Legendre
    nodes the quadrature is exact for polynomials in ``cos theta``, which a
    sphere's area element is.
    """
    nodes, weights = np.polynomial.legendre.leggauss(theta_count)
    theta = np.arccos(nodes)
    phi = (np.arange(phi_count) + 0.5) * (2 * np.pi / phi_count)
    return theta, phi, weights, 2 * np.pi / phi_count


def _directions(theta, phi):
    """Unit vectors ``[3][ntheta][nphi]`` for the ray grid."""
    grid_theta, grid_phi = np.meshgrid(theta, phi, indexing="ij")
    return (
        np.sin(grid_theta) * np.cos(grid_phi),
        np.sin(grid_theta) * np.sin(grid_phi),
        np.cos(grid_theta),
    )


def _sample(field, points, slice_: Slice, order: int = 3):
    """Interpolate a grid field at coordinates measured from the centre."""
    index = np.stack(
        [(points[axis] + slice_.centre[axis]) / slice_.spacing[axis] for axis in INDICES]
    )
    return map_coordinates(np.asarray(field, dtype=float), index, order=order, mode="nearest")


def ray_radii(level_set, slice_: Slice, theta, phi, samples: int = 400, reach: float | None = None):
    """Where ``F`` crosses zero along each ray, by interpolation.

    The outermost crossing is taken, because the apparent horizon is the
    outermost marginally trapped surface and an inner one is a different
    surface. A ray with no crossing gets ``nan``, and the caller decides
    whether that is a failure.

    Neither flow in this module calls this: both carry ``h`` directly and
    have no level set to search. It is here for the other direction -- a
    field computed elsewhere, or an ``F`` whose zero set is wanted as a
    surface -- which is how the trial surfaces in the tests are read back.
    """
    direction = _directions(theta, phi)
    if reach is not None:
        limit = float(reach)
    else:
        # How far a ray can go from the centre before leaving the grid, which
        # is the distance to the nearest face rather than half the box: the
        # centre is deliberately off-centre for staggered puncture data.
        limit = min(
            min(slice_.centre[axis], count * slice_.spacing[axis] - slice_.centre[axis])
            for axis, count in enumerate(slice_.shape)
        )
        limit *= 0.95
    radii = np.linspace(limit / samples, limit, samples)
    points = [direction[axis][..., None] * radii for axis in INDICES]
    values = _sample(level_set, points, slice_)

    out = np.full(direction[0].shape, np.nan)
    sign_change = (values[..., :-1] <= 0.0) & (values[..., 1:] > 0.0)
    for position in range(samples - 1):
        mask = sign_change[..., position]
        if not np.any(mask):
            continue
        low, high = values[..., position][mask], values[..., position + 1][mask]
        fraction = low / (low - high)
        out[mask] = radii[position] + fraction * (radii[position + 1] - radii[position])
    return out


def surface_area(radii, slice_: Slice, theta, phi, weights, phi_weight) -> float:
    """``A = int sqrt(det q) dcos(theta) dphi`` for the surface ``r = h``.

    The induced metric is ``q_ab = gamma_ij d_a x^i d_b x^j`` with
    ``x = centre + h(theta, phi) n(theta, phi)``, so the angular derivatives
    of ``h`` enter -- a surface that is not a coordinate sphere has an area
    the spherical formula gets wrong at second order in its distortion.
    ``d_theta h`` is taken spectrally in ``phi`` and by a Legendre-node
    derivative matrix in ``theta``, so neither is the accuracy bottleneck.
    """
    direction = np.stack(_directions(theta, phi))
    d_theta_direction = np.stack(_directions_dtheta(theta, phi))
    d_phi_direction = np.stack(_directions_dphi(theta, phi))

    d_theta_h = _theta_derivative(radii, theta)
    d_phi_h = _phi_derivative(radii)

    tangent_theta = d_theta_h * direction + radii * d_theta_direction
    tangent_phi = d_phi_h * direction + radii * d_phi_direction

    points = [radii * direction[axis] for axis in INDICES]
    metric = [
        [_sample(slice_.fields[f"gamma{_pair(i, j)}"], points, slice_) for j in INDICES]
        for i in INDICES
    ]

    def inner(left, right):
        return sum(metric[i][j] * left[i] * right[j] for i in INDICES for j in INDICES)

    q_tt = inner(tangent_theta, tangent_theta)
    q_tp = inner(tangent_theta, tangent_phi)
    q_pp = inner(tangent_phi, tangent_phi)
    element = np.sqrt(np.maximum(q_tt * q_pp - q_tp**2, 0.0))
    # dtheta = dcos(theta)/sin(theta), and the Legendre weights are in cos.
    integrand = element / np.sin(theta)[:, None]
    return float(np.sum(integrand * weights[:, None]) * phi_weight)


def _phi_derivative(values) -> np.ndarray:
    """``d/dphi`` spectrally: the ``phi`` grid is uniform and periodic."""
    count = values.shape[-1]
    wavenumber = 2j * np.pi * np.fft.fftfreq(count, d=1.0 / count) / (2 * np.pi)
    return np.real(np.fft.ifft(np.fft.fft(values, axis=-1) * wavenumber, axis=-1))


@lru_cache(maxsize=16)
def _legendre_derivative_matrix(nodes: tuple[float, ...]) -> np.ndarray:
    """The matrix that differentiates the interpolant through ``nodes``.

    Built with Python loops, so it is cached on the node tuple: the angular
    grid is the same every iteration of a flow and rebuilding it each time
    was measurable next to the grid work.
    """
    nodes = np.asarray(nodes, dtype=float)
    count = nodes.size
    matrix = np.zeros((count, count))
    for row in range(count):
        for column in range(count):
            if row == column:
                matrix[row, column] = sum(
                    1.0 / (nodes[row] - nodes[k]) for k in range(count) if k != row
                )
            else:
                weight = np.prod([(nodes[column] - nodes[k]) for k in range(count) if k != column])
                numerator = np.prod(
                    [(nodes[row] - nodes[k]) for k in range(count) if k not in (row, column)]
                )
                matrix[row, column] = numerator / weight
    return matrix


def _theta_derivative(values, theta) -> np.ndarray:
    """``d/dtheta`` by differentiating the interpolant through the nodes.

    The Legendre nodes are not uniform, so a finite difference would be
    first order at the ends. Differentiating the polynomial that passes
    through them is exact for the truncation the grid already implies, and
    ``d/dtheta = -sin(theta) d/dcos(theta)`` converts the result.
    """
    matrix = _legendre_derivative_matrix(tuple(float(value) for value in np.cos(theta)))
    return -np.sin(theta)[:, None] * (matrix @ values)


def _directions_dtheta(theta, phi):
    grid_theta, grid_phi = np.meshgrid(theta, phi, indexing="ij")
    return (
        np.cos(grid_theta) * np.cos(grid_phi),
        np.cos(grid_theta) * np.sin(grid_phi),
        -np.sin(grid_theta),
    )


def _directions_dphi(theta, phi):
    grid_theta, grid_phi = np.meshgrid(theta, phi, indexing="ij")
    return (
        -np.sin(grid_theta) * np.sin(grid_phi),
        np.sin(grid_theta) * np.cos(grid_phi),
        np.zeros_like(grid_theta),
    )


# --- the apparent horizon ------------------------------------------------


@dataclass(frozen=True)
class ApparentHorizon:
    """What the flow converged to.

    ``irreducible_mass`` is ``sqrt(A / 16 pi)``, which for Schwarzschild is
    the mass and in general is the quantity that cannot decrease. It is the
    number worth comparing between runs: a coordinate radius is not
    meaningful on its own and an area is.

    ``residual`` is ``max|Theta|`` over the surface, in the grid's units. It
    is the honest measure of whether this is a horizon: a flow that ran out
    of iterations still returns a surface.
    """

    radii: np.ndarray
    area: float
    residual: float
    iterations: int
    converged: bool

    @property
    def irreducible_mass(self) -> float:
        return float(np.sqrt(self.area / (16.0 * np.pi)))

    @property
    def mean_radius(self) -> float:
        return float(np.mean(self.radii))

    @property
    def distortion(self) -> float:
        """``(max - min)/mean`` of the radius: zero for a coordinate sphere."""
        return float((np.max(self.radii) - np.min(self.radii)) / np.mean(self.radii))

    def summary(self) -> dict[str, float]:
        return {
            "area": self.area,
            "irreducible_mass": self.irreducible_mass,
            "mean_radius": self.mean_radius,
            "distortion": self.distortion,
            "residual": self.residual,
            "iterations": float(self.iterations),
            "converged": float(self.converged),
        }


def _monomial_exponents(degree: int) -> tuple[tuple[int, int, int], ...]:
    """Exponents of the monomials in a unit direction, up to ``degree``.

    Monomials in ``(n_x, n_y, n_z)`` of total degree at most ``d``, restricted
    to the unit sphere, span exactly the spherical harmonics with ``l <= d``.
    So this is a spherical-harmonic representation of the surface without any
    associated Legendre functions: the basis is evaluated on the Cartesian
    grid with a couple of multiplications per term, where ``Y_lm`` would
    need a special function at every one of ``n^3`` points and be
    precomputed into a hundred megabytes to stay affordable.
    """
    return tuple(
        (a, b, c)
        for a in range(degree + 1)
        for b in range(degree + 1 - a)
        for c in range(degree + 1 - a - b)
    )


def _monomials(direction, exponents) -> list[np.ndarray]:
    """Evaluate the basis on a triple of direction-component arrays."""
    degree = max(sum(term) for term in exponents)
    powers = [[np.ones_like(direction[axis])] + [None] * degree for axis in INDICES]
    for axis in INDICES:
        for order in range(1, degree + 1):
            powers[axis][order] = powers[axis][order - 1] * direction[axis]
    return [powers[0][a] * powers[1][b] * powers[2][c] for a, b, c in exponents]


def find_apparent_horizon(
    slice_: Slice,
    guess: float,
    theta_count: int = 24,
    phi_count: int = 48,
    tolerance: float = 1e-3,
    max_iterations: int = 200,
    safety: float = 0.5,
    degree: int = 2,
) -> ApparentHorizon:
    """Flow a trial sphere of radius ``guess`` until its expansion vanishes.

    The surface is a radius per direction, ``h(theta, phi)``, and the flow is
    ``dh/dlambda = -Theta``: a surface whose outward null expansion is
    positive shrinks, one inside a horizon grows, and ``Theta = 0`` is the
    fixed point. ``degree`` sets the angular resolution of ``h`` -- the same
    span as spherical harmonics up to ``l = degree`` -- and projecting onto
    that basis every iteration is also what keeps angular noise out of the
    flow. It is not free: the stable step falls as ``1/degree^2`` (see
    below), so following a distorted surface costs iterations quadratically.
    Two is enough for anything near a coordinate sphere, which is what a
    single hole centred on its own rays is; a surface whose radius varies
    across directions wants four and about three times the iterations.

    **Why the radius and not the level-set field.** The obvious
    implementation evolves ``F`` on the grid by ``dF/dlambda = Theta|grad F|``
    and reads the surface off as ``F = 0``. It does not work, for two
    reasons that both took measuring. The gradient factor is a feedback
    loop -- a distorting field has a larger gradient, which lengthens the
    step, which distorts it more -- and ``max|dF|`` ran 1.4e-2, 7.2e-2, 0.75,
    15, 145, up to 1.5e5 in sixty iterations. Removing it is not enough: a
    spatially varying step puts structure into ``grad grad F``, which is
    what the divergence term of ``Theta`` differentiates, so the surface's
    own residual climbs. Measured, the first four iterations moved at
    exactly the intended 1.6e-2 per step and then the residual jumped from
    0.27 to 1.22 and oscillated between 0.7 and 4.0 while the flow stalled
    at 1e-4 per step. Flowing ``h`` and rebuilding ``F = r - h`` each
    iteration means the field is a clean radial function every time and
    carries no history at all, which is a stronger statement than
    reinitialising it would be.

    It also confines the under-resolved region to where it cannot matter. A
    few cells from a puncture the grid reports ``Theta = -1.32`` where the
    analytic value tends to zero; ``Theta`` is only ever *sampled* on the
    surface, so that never enters.

    ``tolerance`` is on ``max|Theta|`` over the surface, in grid units, and
    cannot be met below the grid's own error -- at a spacing of 0.083 the
    expansion of the exact horizon evaluates to 5.6e-3 rather than zero, so
    asking for 1e-3 there is asking the flow to find a surface that does not
    exist on that grid. :func:`schwarzschild_slice`'s convergence table is
    the guide to what a given spacing can deliver.

    Returns even when it does not converge, with ``converged=False`` and the
    residual it reached -- a caller doing this every few steps of an
    evolution wants the best surface so far, not an exception.
    """
    theta, phi, weights, phi_weight = angular_grid(theta_count, phi_count)
    direction = _directions(theta, phi)
    exponents = _monomial_exponents(degree)
    design = np.stack([term.ravel() for term in _monomials(direction, exponents)], axis=-1)

    coords = slice_.coordinates()
    grid_radius = np.sqrt(sum(value**2 for value in coords))
    if np.any(grid_radius <= 0.0):
        raise ValueError(
            "a grid point sits exactly on the centre rays are cast from, where "
            "the direction is undefined; stagger the centre by half a cell"
        )
    grid_monomials = _monomials([value / grid_radius for value in coords], exponents)

    radii = np.full(direction[0].shape, float(guess), dtype=float)
    reach = min(
        min(slice_.centre[axis], count * slice_.spacing[axis] - slice_.centre[axis])
        for axis, count in enumerate(slice_.shape)
    )

    best_radii: np.ndarray | None = None
    best_residual = np.inf
    relaxation: float | None = None
    used = 0

    def finish(surface, residual, iterations, converged) -> ApparentHorizon:
        area = surface_area(surface, slice_, theta, phi, weights, phi_weight)
        return ApparentHorizon(surface, area, residual, iterations, converged)

    for iteration in range(1, max_iterations + 1):
        used = iteration
        coefficients, *_ = np.linalg.lstsq(design, radii.ravel(), rcond=None)
        radii = (design @ coefficients).reshape(radii.shape)
        if np.any(radii <= 0.0) or np.any(radii >= reach):
            if best_radii is not None:
                return finish(best_radii, best_residual, iteration, False)
            raise RuntimeError(
                f"the trial surface left the grid after {iteration} iterations, "
                f"reaching a radius of {float(np.max(radii)):.3g} against a "
                f"usable {reach:.3g}; try a guess nearer the horizon or a "
                "smaller safety factor"
            )

        field = grid_radius - sum(
            weight * term for weight, term in zip(coefficients, grid_monomials, strict=True)
        )
        theta_field = expansion(field, slice_)
        on_surface = _sample(theta_field, [radii * value for value in direction], slice_)
        residual = float(np.max(np.abs(on_surface)))
        if residual < best_residual:
            best_radii, best_residual = radii.copy(), residual
        if residual < tolerance:
            return finish(radii, residual, iteration, True)
        if not np.isfinite(residual) or residual == 0.0:
            return finish(radii, residual, iteration, residual < tolerance)

        # The relaxation is fixed from the *first* residual rather than the
        # current one. Rescaling every iteration makes the largest step
        # ``safety`` of a cell however small the residual has become, so the
        # flow arrives and then oscillates about the answer with that
        # amplitude; holding it fixed makes this plain gradient descent,
        # ``dh/dlambda = -Theta``, which contracts geometrically instead.
        if relaxation is None:
            relaxation = safety * min(slice_.spacing) / residual

        # **And it is capped by a parabolic stability limit.** ``Theta``
        # contains the surface Laplacian of ``h``, so this flow is a heat
        # equation on the sphere -- which is what makes it converge at all,
        # and also what makes an explicit step conditionally stable. The
        # angular Laplacian's eigenvalues are ``-l(l+1)/h^2``, so the limit
        # is ``lambda < 2 h^2 / (l_max (l_max + 1))`` with ``l_max`` the
        # degree of the basis.
        #
        # Getting this wrong does not look like an instability, it looks like
        # a bad guess. Measured from ``h = 0.9``, the step sat at 3.9 times
        # the limit and converged anyway; from ``h = 0.3`` it sat at 27
        # times and the surface distorted to a minimum of 0.21 against a
        # maximum of 0.53 and then oscillated with period two forever,
        # reporting its own initial guess back. The limit scales as ``h^2``,
        # which is why a guess deep inside is the expensive one: it has the
        # smallest stable step and the furthest to go.
        if degree > 0:
            limit = float(np.min(radii)) ** 2 / (degree * (degree + 1))
            relaxation = min(relaxation, safety * limit)
        radii = radii - relaxation * on_surface

    assert best_radii is not None
    return finish(best_radii, best_residual, used, False)


def _gradient_norm(field, slice_: Slice) -> np.ndarray:
    inverse = slice_.inverse_metric()
    gradient = [derivative(field, i, slice_.spacing[i], order=slice_.order) for i in INDICES]
    return np.sqrt(
        np.maximum(
            sum(inverse[i][j] * gradient[i] * gradient[j] for i in INDICES for j in INDICES),
            0.0,
        )
    )


# --- the event horizon ---------------------------------------------------


def null_rate(level_set, slice_: Slice) -> np.ndarray:
    """``d_t F`` for an outgoing null surface: ``beta^i d_i F - alpha |grad F|``.

    From ``g^ab d_a F d_b F = 0`` written in ADM form, whose two roots are
    the ingoing and outgoing surfaces. With ``F`` increasing outwards the
    outgoing one is the minus branch: for static Schwarzschild in isotropic
    coordinates it gives ``dh/dt = alpha/psi^2``, which is positive outside
    the horizon and zero exactly on it.
    """
    field = np.asarray(level_set, dtype=float)
    gradient = [derivative(field, i, slice_.spacing[i], order=slice_.order) for i in INDICES]
    lapse = np.asarray(slice_.fields.get("alpha", 1.0), dtype=float)
    advection = np.zeros_like(field)
    for i in INDICES:
        shift = slice_.fields.get(f"beta{i}")
        if shift is not None:
            advection = advection + np.asarray(shift, dtype=float) * gradient[i]
    return advection - lapse * _gradient_norm(field, slice_)


def event_horizon_flow(
    slices: Slice | Sequence[Slice] | Callable[[int], Slice],
    guess: float,
    time_step: float,
    steps: int,
    theta_count: int = 16,
    phi_count: int = 32,
    degree: int = 2,
) -> list[tuple[float, np.ndarray]]:
    """Integrate an outgoing null surface *backwards* in time.

    ``slices`` is the spacetime, latest first: a sequence of slices, a
    callable of the step index, or a single slice for a static spacetime.
    Time runs backwards, so entry ``k`` is the slice at ``t = -k dt``
    relative to where the integration starts.

    The returned history is ``(time, radii)`` with time going negative, so
    the last entry is the earliest surface and the one that has settled onto
    the horizon. Started outside, the surface falls inwards onto it; started
    inside, it climbs out. Two-sided convergence is what distinguishes the
    event horizon from somewhere a null surface happened to sit.

    **Why backwards.** Outgoing null surfaces near the horizon separate from
    it towards the future at the surface gravity, so forward integration
    loses it exponentially fast and no accuracy fixes that. Backwards, the
    same exponential is a contraction. Nothing about the initial guess has
    to be right except which side of the horizon it is on.

    **The radius, not the level-set field.** ``d_t F = beta^i d_i F -
    alpha |grad F|`` is a Hamilton-Jacobi equation, and steepening gradients
    is what those do: integrated as a grid field it overflowed to ``inf``
    and then ``NaN``. Since ``F = r - h(t, n)`` gives ``d_t F = -d_t h`` at
    fixed position, the same condition reads

        d_t h = alpha |grad F|_gamma - beta^i d_i F

    sampled on the surface, and evolving ``h`` rebuilds a clean radial field
    every stage. Same reason as :func:`find_apparent_horizon`, same fix, and
    here it is not a matter of stability but of the equation being able to
    run at all.

    **Not a merger.** One radius per direction follows one star-shaped
    horizon. A binary's event horizon is not star-shaped before the merger,
    and what this would report is the outermost crossing of a ray through a
    two-piece surface, which is not so much wrong as meaningless.
    """
    if callable(slices):
        at_step = slices
    elif isinstance(slices, Slice):
        at_step = lambda _: slices  # noqa: E731
    else:
        sequence = list(slices)
        at_step = lambda index: sequence[min(int(index), len(sequence) - 1)]  # noqa: E731

    first = at_step(0)
    theta, phi, _, _ = angular_grid(theta_count, phi_count)
    direction = _directions(theta, phi)
    exponents = _monomial_exponents(degree)
    design = np.stack([term.ravel() for term in _monomials(direction, exponents)], axis=-1)
    coords = first.coordinates()
    grid_radius = np.sqrt(sum(value**2 for value in coords))
    grid_monomials = _monomials([value / grid_radius for value in coords], exponents)

    def rate(surface, slice_):
        """``d_t h`` on the surface, from a field rebuilt for this radius."""
        coefficients, *_ = np.linalg.lstsq(design, surface.ravel(), rcond=None)
        field = grid_radius - sum(
            weight * term for weight, term in zip(coefficients, grid_monomials, strict=True)
        )
        sampled = _sample(null_rate(field, slice_), [surface * v for v in direction], slice_)
        return -sampled

    radii = np.full(direction[0].shape, float(guess), dtype=float)
    history = [(0.0, radii.copy())]
    for step in range(1, steps + 1):
        current, following = at_step(step - 1), at_step(step)
        # Midpoint, and backwards: subtract rather than add.
        half = radii - 0.5 * time_step * rate(radii, current)
        radii = radii - time_step * rate(half, following)
        if not np.all(np.isfinite(radii)) or np.any(radii <= 0.0):
            break
        history.append((-step * time_step, radii.copy()))
    return history


# --- exact data to test against ------------------------------------------


def schwarzschild_slice(
    shape=(64, 64, 64),
    extent: float = 8.0,
    mass: float = 1.0,
    stagger: bool = True,
) -> Slice:
    """Static Schwarzschild in isotropic coordinates, exactly.

    ``gamma_ij = psi^4 delta_ij`` with ``psi = 1 + M/(2r)``, ``K_ij = 0``,
    and the *static* lapse ``alpha = (1 - M/2r)/(1 + M/2r)``. That lapse is
    what makes the event horizon computable from one slice: with ``alpha = 1``
    the slicing is not static, a single slice does not determine the
    spacetime, and there is nothing for a null surface to converge to.

    The apparent horizon is at ``r = M/2``, where ``psi = 2``, so the area is
    ``psi^4 r^2 4 pi = 16 pi M^2`` and the irreducible mass is ``M`` -- three
    exact numbers to check against, none of them zero.

    ``stagger`` offsets the centre by half a cell, as
    :func:`particlesim.solvers.nr.bssn.brill_lindquist` does, because ``psi``
    is infinite at ``r = 0`` and an even shape puts a sample on the box
    centre.
    """
    counts = tuple(int(value) for value in np.atleast_1d(shape))
    if len(counts) == 1:
        counts = counts * DIMENSION
    spacing = tuple(extent / count for count in counts)
    centre = tuple(extent / 2 + (spacing[axis] / 2 if stagger else 0.0) for axis in INDICES)
    axes = [np.arange(counts[axis]) * spacing[axis] - centre[axis] for axis in INDICES]
    mesh = np.meshgrid(*axes, indexing="ij")
    radius = np.sqrt(sum(value**2 for value in mesh))
    if np.any(radius <= 0.0):
        raise ValueError(
            "a grid point sits exactly on the puncture, where psi is infinite; "
            "use stagger=True or an odd shape"
        )

    conformal = 1.0 + mass / (2.0 * radius)
    factor = conformal**4
    fields: dict[str, Any] = {
        "alpha": (1.0 - mass / (2.0 * radius)) / (1.0 + mass / (2.0 * radius)),
    }
    for i in INDICES:
        fields[f"beta{i}"] = np.zeros_like(radius)
        for j in range(i, DIMENSION):
            fields[f"gamma{i}{j}"] = factor if i == j else np.zeros_like(radius)
            fields[f"K{i}{j}"] = np.zeros_like(radius)
    return Slice(fields=fields, spacing=spacing, centre=centre)


__all__ = [
    "ApparentHorizon",
    "Slice",
    "angular_grid",
    "event_horizon_flow",
    "expansion",
    "find_apparent_horizon",
    "null_rate",
    "ray_radii",
    "schwarzschild_slice",
    "surface_area",
]
